version: '3.9'
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db
    environment:
      - APP_PROFILE=${APP_PROFILE}
      - DB_URL=${DB_URL:-jdbc:postgresql://db:${DB_PORT}/stocks_db}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - POLYGON_TOKEN=${POLYGON_TOKEN}

  db:
    image: postgres:17.0
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_DB_NAME:-stocks_db}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USERNAME=${DB_USERNAME}
    volumes:
      - ./db_data:/var/lib/postgres
    command: -p ${DB_PORT}